version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run start:dev
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./front-end
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development
